# Generated by Django 3.2.7 on 2021-09-15 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geocache", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placecache",
            name="address",
            field=models.CharField(max_length=100, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="placecache",
            name="distance",
            field=models.FloatField(verbose_name="Расстояние"),
        ),
        migrations.AlterField(
            model_name="placecache",
            name="last_update",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата последнего обновления",
            ),
        ),
    ]
