# Generated by Django 3.2.6 on 2021-09-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_processed',
            field=models.BooleanField(choices=[(True, 'Обработано'), (False, 'Необработано')], default=False),
        ),
    ]
