# Generated by Django 3.2.7 on 2021-09-15 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0044_alter_order_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="called_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(null=True),
        ),
    ]
