# Generated by Django 3.2.7 on 2021-09-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0045_auto_20210915_1447"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.BooleanField(
                choices=[(True, "Наличными"), (False, "Электронно")],
                default=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="called_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
