# Generated by Django 3.2.7 on 2021-09-16 21:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foodcartapp", "0049_auto_20210915_2256"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Цена товара",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Общая цена",
                    ),
                ),
            ],
            options={
                "verbose_name": "позиция",
                "verbose_name_plural": "позиции",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Комментарий к заказу"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.CharField(
                choices=[("CASH", "Наличными"), ("CARD", "Электронно")],
                default="CARD",
                max_length=30,
                verbose_name="Вид оплаты",
            ),
        ),
        migrations.DeleteModel(
            name="OrderedProduct",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="foodcartapp.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="order_items",
                to="foodcartapp.product",
                verbose_name="Товар",
            ),
        ),
    ]
